title: 海外软件技术教程
description: 提供全球软件技术交流知识，涵盖电报、纸飞机、推特等多个海外平台，深入探讨油管、YouTube、Facebook等内容。欧易和币安的使用教程，节点返佣等实用信息全面解读。如需技术支持，请添加 QQ 联系 1702242347，加了没同意，请加 2928893676，无法加Q，请右下角联系。
show_downloads: true

baseurl: "/docs" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://tggsearch.org" # change this to the base hostname & protocol for your site
permalink: /docs/:title.html

google_analytics: G-61CEYEJKCR

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%Y-%m-%d"

theme: # leave it empty

disqus_shortname: https-tggsearch-org

# social
author: 小青
image: /thumbnail-jumbo.png
twitter:
  username: idanhua
 
plugins:
  - jekyll-target-blank
  - jekyll-paginate
  - jekyll-seo-tag

target-blank:
    rel: nofollow

# Paginate
paginate: 10
paginate_path: "docs/page:num"

header_page_refs: [{'id' : 'telegram', 'name': '电报'}, {'id': 'twitter', 'name': '推特'}, {'id': 'youtube', 'name': '油管'}, {'id': 'exchange', 'name': '交易所'}, {'id': 'account', 'name': '账号类'}, {'id': 'line', 'name': 'line'}, {'id': 'about', 'name': '关于我们'}, {'id': 'index', 'name': '返回首页'}]
