const axios = require('axios');

const requestData = {
  host: 'tggsearch.gtihub.io',
  key: '587a71a7fbd743a68771ca6d9bbc6fe2',
  keyLocation: 'https://tggsearch.gtihub.io/587a71a7fbd743a68771ca6d9bbc6fe2.txt',
  urlList: [
    "https://tggsearch.gtihub.io/",
    "https://tggsearch.gtihub.io/telegram.html",
    "https://tggsearch.gtihub.io/twitter.html",
    "https://tggsearch.gtihub.io/account.html",
    "https://tggsearch.gtihub.io/exchange.html",
    "https://tggsearch.gtihub.io/youtube.html",
    "https://tggsearch.gtihub.io/line.html",
    "https://tggsearch.gtihub.io/docs/vpn-kl.html",
    "https://tggsearch.gtihub.io/docs/news-ygg.html",
    "https://tggsearch.gtihub.io/docs/pay-bot-en.html",
    "https://tggsearch.gtihub.io/docs/telegram-begain.html",
    "https://tggsearch.gtihub.io/docs/telegram-mb.html",
    "https://tggsearch.gtihub.io/docs/apple-id.html",
    "https://tggsearch.gtihub.io/docs/okx-buy-coins.html",
    "https://tggsearch.gtihub.io/docs/tiktok.html",
    "https://tggsearch.gtihub.io/docs/telegram-desktop.html",
    "https://tggsearch.gtihub.io/docs/telegram-start.html",
    "https://tggsearch.gtihub.io/docs/okx-act.html",
    "https://tggsearch.gtihub.io/docs/pay-bot-cn.html",
    "https://tggsearch.gtihub.io/docs/jpex.html",
    "https://tggsearch.gtihub.io/docs/telegram-deive-code.html",
    "https://tggsearch.gtihub.io/docs/register.html",
    "https://tggsearch.gtihub.io/docs/telegram-android.html",
    "https://tggsearch.gtihub.io/docs/ok-gd.html",
    "https://tggsearch.gtihub.io/docs/okx-afi.html",
    "https://tggsearch.gtihub.io/docs/okx-error.html",
    "https://tggsearch.gtihub.io/docs/twitter-ranking.html",
    "https://tggsearch.gtihub.io/docs/register-apple-id.html",
    "https://tggsearch.gtihub.io/docs/telegram-account.html",
    "https://tggsearch.gtihub.io/docs/huobi-act.html",
    "https://tggsearch.gtihub.io/docs/telegram-search.html",
    "https://tggsearch.gtihub.io/docs/telegram-group-spc.html",
    "https://tggsearch.gtihub.io/docs/telegram-apk.html",
    "https://tggsearch.gtihub.io/docs/high-end-info.html",
    "https://tggsearch.gtihub.io/docs/betrays.html",
    "https://tggsearch.gtihub.io/docs/bnb-buy-coins.html",
    "https://tggsearch.gtihub.io/docs/usdt.html",
    "https://tggsearch.gtihub.io/docs/coins-yx-play.html",
    "https://tggsearch.gtihub.io/docs/huobi-download.html",
    "https://tggsearch.gtihub.io/docs/okx-safety.html",
    "https://tggsearch.gtihub.io/docs/telegram-bot.html",
    "https://tggsearch.gtihub.io/docs/telegram-premium.html",
    "https://tggsearch.gtihub.io/docs/bnb-coins.html",
    "https://tggsearch.gtihub.io/docs/buyu-selleru.html",
    "https://tggsearch.gtihub.io/docs/coins-new.html",
    "https://tggsearch.gtihub.io/docs/new-blockchain.html",
    "https://tggsearch.gtihub.io/docs/okx.html",
    "https://tggsearch.gtihub.io/docs/telegram-luo.html",
    "https://tggsearch.gtihub.io/docs/twitter-register.html",
    "https://tggsearch.gtihub.io/docs/usdt-make-money.html",
    "https://tggsearch.gtihub.io/docs/telegram-ios.html",
    "https://tggsearch.gtihub.io/docs/vpn.html",
    "https://tggsearch.gtihub.io/docs/airdrop.html",
    "https://tggsearch.gtihub.io/docs/okx-intro.html",
    "https://tggsearch.gtihub.io/docs/telegram-cn.html",
    "https://tggsearch.gtihub.io/docs/telegram-group.html",
    "https://tggsearch.gtihub.io/docs/coins-index.html",
    "https://tggsearch.gtihub.io/docs/telegram-not-join.html",
    "https://tggsearch.gtihub.io/docs/twitter-register-error.html",
    "https://tggsearch.gtihub.io/docs/twitter-spc.html",
    "https://tggsearch.gtihub.io/docs/twitter-video-download.html",
    "https://tggsearch.gtihub.io/docs/usdt-buy.html",
    "https://tggsearch.gtihub.io/docs/yx-hy.html",
    "https://tggsearch.gtihub.io/docs/huobi-transfer.html",
    "https://tggsearch.gtihub.io/docs/receive-code.html",
    "https://tggsearch.gtihub.io/docs/telegram-account-buy.html",
    "https://tggsearch.gtihub.io/docs/telegram-add-friends.html",
    "https://tggsearch.gtihub.io/docs/telegram-scam.html",
    "https://tggsearch.gtihub.io/docs/trx.html",
    "https://tggsearch.gtihub.io/docs/twitter-intro.html",
    "https://tggsearch.gtihub.io/docs/twitter.html",
    "https://tggsearch.gtihub.io/docs/btc.html",
    "https://tggsearch.gtihub.io/docs/buyu-help.html",
    "https://tggsearch.gtihub.io/docs/coins-yx-intro.html",
    "https://tggsearch.gtihub.io/docs/huobi.html",
    "https://tggsearch.gtihub.io/docs/huobi-buy-coins.html",
    "https://tggsearch.gtihub.io/docs/recover-id.html",
    "https://tggsearch.gtihub.io/docs/telegram-download.html",
    "https://tggsearch.gtihub.io/docs/telegram-ch.html",
    "https://tggsearch.gtihub.io/docs/telegram-pay.html",
    "https://tggsearch.gtihub.io/docs/twitter-login.html",
    "https://tggsearch.gtihub.io/docs/twitter-excel.html",
    "https://tggsearch.gtihub.io/docs/twitter-api.html"]  
};

axios.post('https://api.indexnow.org/IndexNow', requestData, {
  headers: {
    'Content-Type': 'application/json; charset=utf-8',
    'Host': 'api.indexnow.org'
  }
})
.then(response => {
  console.log('Response:', response.data);
})
.catch(error => {
  console.error('Error:', error);
});
